### ISSUE TITLE
Make plain SQL safer

### ISSUE THREAD

**Issue by d6y** [lashchenko/demo-scala-multidb-slick-guice#1]
Hello!

Thanks for creating and sharing this repository. Super useful.

I noticed in `plainSqlCountByName` [DemoDbTables.scala](https://github.com/lashchenko/demo-scala-multidb-slick-guice/blob/master/src/main/scala/com/github/lashchenko/DemoDbTables.scala#L73-L76) you use a splice (`'#$name'`).   

Unless there's a good reason for that, you might want to change the example to use a regular interpolated value. E.g.

```scala
val q = sql"SELECT count(*) FROM DEMO where name = $name".as[Int].headOption
```

My thinking is that `$name` could come from a user, and if so, [it could contain SQL and would be unsafe](https://www.xkcd.com/327/) to use in this query.

**Comment by lashchenko** [comment]
Fixed. Thank you.
